// <auto-generated />
using System;
using MafTi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MafTi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906142154_ActualizarTrabajador")]
    partial class ActualizarTrabajador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MafTi.Domain.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionCorporativaId")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionDomicilio")
                        .HasColumnType("text");

                    b.Property<bool>("EsCuentaGenerica")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaIncorporacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("HomologarAccesosDesde")
                        .HasColumnType("text");

                    b.Property<string>("JefeDirecto")
                        .HasColumnType("text");

                    b.Property<int>("LugarTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SolicitaTelefono")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneTelefonoCorporativo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Trabajadores");
                });
#pragma warning restore 612, 618
        }
    }
}
