// <auto-generated />
using System;
using MafTi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MafTi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911124250_AgregarRelacionesTrabajadorCatalogo")]
    partial class AgregarRelacionesTrabajadorCatalogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MafTi.Domain.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaOtorgado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("MafTi.Domain.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalogos");
                });

            modelBuilder.Entity("MafTi.Domain.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimientoSLA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<int?>("SolicitudOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("SolicitudOrigenId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("MafTi.Domain.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionCorporativaId")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionDomicilio")
                        .HasColumnType("text");

                    b.Property<bool>("EsCuentaGenerica")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaIncorporacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("HomologarAccesosDesde")
                        .HasColumnType("text");

                    b.Property<string>("JefeDirecto")
                        .HasColumnType("text");

                    b.Property<int>("LugarTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SolicitaTelefono")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneTelefonoCorporativo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DireccionCorporativaId");

                    b.HasIndex("LugarTrabajoId");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("MafTi.Domain.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("CorreoAD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("MafTi.Domain.Acceso", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Catalogo")
                        .WithMany()
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId");

                    b.HasOne("MafTi.Domain.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("Solicitud");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MafTi.Domain.Solicitud", b =>
                {
                    b.HasOne("MafTi.Domain.UsuarioSistema", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "SolicitudOrigen")
                        .WithMany()
                        .HasForeignKey("SolicitudOrigenId");

                    b.HasOne("MafTi.Domain.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("SolicitudOrigen");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MafTi.Domain.Trabajador", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Catalogo", "DireccionCorporativa")
                        .WithMany()
                        .HasForeignKey("DireccionCorporativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Catalogo", "LugarTrabajo")
                        .WithMany()
                        .HasForeignKey("LugarTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("DireccionCorporativa");

                    b.Navigation("LugarTrabajo");
                });

            modelBuilder.Entity("MafTi.Domain.UsuarioSistema", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
