// <auto-generated />
using System;
using MafTi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MafTi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009135018_AgregarSolicitudBloqueo")]
    partial class AgregarSolicitudBloqueo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MafTi.Domain.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaOtorgado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("MafTi.Domain.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PadreId");

                    b.ToTable("Catalogos");
                });

            modelBuilder.Entity("MafTi.Domain.HistorialSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RealizadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RealizadoPorId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("HistorialSolicitudes");
                });

            modelBuilder.Entity("MafTi.Domain.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("MafTi.Domain.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MafTi.Domain.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("RolPermisos");
                });

            modelBuilder.Entity("MafTi.Domain.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimientoSLA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<int?>("SolicitudOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("SolicitudOrigenId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("MafTi.Domain.SolicitudBloqueo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CasillaOpera")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsTemporal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<bool?>("TienePc")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.ToTable("SolicitudesBloqueo");
                });

            modelBuilder.Entity("MafTi.Domain.SolicitudDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogoId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudDetalles");
                });

            modelBuilder.Entity("MafTi.Domain.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionCorporativaId")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionDomicilio")
                        .HasColumnType("text");

                    b.Property<bool>("EsCuentaGenerica")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaIncorporacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<string>("HomologarAccesosDesde")
                        .HasColumnType("text");

                    b.Property<string>("JefeDirecto")
                        .HasColumnType("text");

                    b.Property<int>("LugarTrabajoId")
                        .HasColumnType("integer");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SolicitaTelefono")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneTelefonoCorporativo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("DireccionCorporativaId");

                    b.HasIndex("LugarTrabajoId");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("MafTi.Domain.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("RolId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("MafTi.Domain.Acceso", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Catalogo")
                        .WithMany()
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId");

                    b.HasOne("MafTi.Domain.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("Solicitud");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MafTi.Domain.Catalogo", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Padre")
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("MafTi.Domain.HistorialSolicitud", b =>
                {
                    b.HasOne("MafTi.Domain.UsuarioSistema", "RealizadoPor")
                        .WithMany()
                        .HasForeignKey("RealizadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealizadoPor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MafTi.Domain.RolPermiso", b =>
                {
                    b.HasOne("MafTi.Domain.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MafTi.Domain.Solicitud", b =>
                {
                    b.HasOne("MafTi.Domain.UsuarioSistema", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "SolicitudOrigen")
                        .WithMany()
                        .HasForeignKey("SolicitudOrigenId");

                    b.HasOne("MafTi.Domain.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("SolicitudOrigen");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MafTi.Domain.SolicitudBloqueo", b =>
                {
                    b.HasOne("MafTi.Domain.Solicitud", "Solicitud")
                        .WithOne()
                        .HasForeignKey("MafTi.Domain.SolicitudBloqueo", "SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MafTi.Domain.SolicitudDetalle", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Catalogo")
                        .WithMany()
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalogo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("MafTi.Domain.Trabajador", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Catalogo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Catalogo", "DireccionCorporativa")
                        .WithMany()
                        .HasForeignKey("DireccionCorporativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Catalogo", "LugarTrabajo")
                        .WithMany()
                        .HasForeignKey("LugarTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");

                    b.Navigation("DireccionCorporativa");

                    b.Navigation("LugarTrabajo");
                });

            modelBuilder.Entity("MafTi.Domain.UsuarioSistema", b =>
                {
                    b.HasOne("MafTi.Domain.Catalogo", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("MafTi.Domain.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafTi.Domain.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Rol");

                    b.Navigation("Trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
